launch:
  broadcast: 192.168.88.255
  defaultBroadcastPort: 10003
  serialPort: /dev/ttyACM0
  baudRate: 115200
topsides:
  pilotPanelName: Pilot Panel
  pilotPanelPort: /dev/ttyACM0
  pilotPanelTimeOut: 2000
  pilotPanelBaud: 115200
  pilotPanelHeartbeatInterval: 500
  pilotPanelHeartbeatTimeout: 5000
  pilotPanelOutputs: [22,24,26,28,30,32,34,36,38,53]
  pilotPanelInputPullups: [23,25,27,29,31,33,35,37,39]
  joystickRecoveryInterval: 1000
  emergencyStopButtonAddress: 53
  profileSwitchDuration: 2000
  profilePref: profiles
rov:
  maxHeartbeatGap: 5
  cpuPollInterval: 1
  sensorPollInterval: 10
  sleepDuration: 100
  maestroDeviceNumber: 0x01
  portAftChannel: 17
  starboardAftChannel: 2
  portForeChannel: 15
  starboardForeChannel: 1
  vertAftChannel: 0
  vertForeChannel: 16
  cameraAMotorChannel: 7
  cameraBMotorChannel: 6
  toolingMotorChannel: 22
  lightChannel: 23
  altImuSa0High: false
  i2cBus: 1
  shutdownTimeout: 1000
videoDecoder:
  host: 192.168.88.2
  cameraAVideoPort: 12345
  cameraBVideoPort: 12346
  format: h264
  frameRate: 96
  socketBacklog: 100
joystick:
  cameraAMotorForwardButton: 4
  cameraAMotorReverseButton: 6
  cameraBMotorForwardButton: 5
  cameraBMotorReverseButton: 3
  toolingMotorForwardButton: 11
  toolingMotorReverseButton: 12
  motionReverseButton: 2
  cameraAVideoFlipButton: 8
  cameraBVideoFlipButton: 7
  motorRotationSpeed: 0.3f
slider:
  globalPowerSliderAddress: 3
  heavePowerSliderAddress: 2
  swayPowerSliderAddress: 1
  surgePowerSliderAddress: 0
  pitchPowerSliderAddress: 4
  yawPowerSliderAddress: 5
  lightPowerSliderAddress: 7
