- hosts: captain
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install htop
      apt: name=htop state=latest
    - name: Install nmap
      apt: name=nmap state=latest
    - name: Install OpenJDK 8
      apt: name=openjdk-8-jdk state=latest
      tags: java
    - name: Install Open JavaFX
      apt: name=openjfx state=latest
      tags: java
    - name: Add Gradle repo
      apt_repository: repo='ppa:cwchien/gradle'
      tags:
        - optional
        - java
    - name: Install Gradle
      apt: name=gradle-2.14 state=latest
      tags:
        - optional
        - java
    - name: Remove old Java certificates
      command: dpkg --purge --force-depends ca-certificates-java
      tags: java
    - name: Install latest Java certificates
      apt: name=ca-certificates-java state=latest
      tags: java
    - name: Install Squid Proxy
      apt: name=squid3 state=latest
    - name: Configure Squid Proxy
      copy: src=files/conf/squid.conf dest=/etc/squid/squid.conf mode=644 owner=root group=root
      notify: Restart Squid
  handlers:
    - name: Restart Squid
      service: name=squid state=restarted
