- hosts: topside:rasprime:picamera
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    version: "9.0.0"
  tasks:
    - name: Make opt directory
      file: path=/opt state=directory mode=0755
    - name: Copy Control Software
      unarchive: src=../build/distributions/eer-{{ version }}.zip dest=/opt
    - name: Copy Config Files
      template: src=files/{{ item }} dest=/opt/eer-{{ version }}/{{ item }} mode=755 owner={{ ansible_user }} group={{ ansible_user }}
      with_items:
        - config.yml
        - defaultConfig.yml

- hosts: rasprime:picamera
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    version: "9.0.0"
  tasks:
    - name: Copy unit file for systemd
      template: src=files/etc/systemd/system/eer.service dest=/etc/systemd/system/eer.service mode=644
      notify:
        - Reload systemd
        - Enable eer service
  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
    - name: Enable eer service
      command: systemctl enable eer.service

- hosts: rasprime:picamera
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Restart eer service
      service: name=eer state=restarted

- hosts: topside
  gather_facts: no
  tasks:
    - name: Make a pretty launcher for da NOOBS
      copy: src=files/Launcher.desktop dest=~/Desktop mode=700
