- hosts: topside:rasprime:picamera
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Copy Control Software
      copy: src=../build/libs/eer-{{ version }}.jar dest=/opt/eer-{{ version }}/libs/eer-{{ version }}.jar
    - name: Copy Default Config File
      copy: src=files/defaultConfig.yml dest=/opt/eer-{{ version }}/defaultConfig.yml mode=755 owner={{ ansible_user }} group={{ ansible_user }}
    - name: Verify Custom Config Exists
      file: path=/home/{{ ansible_user }}/config.yml state=touch mode=755 owner={{ ansible_user }} group={{ ansible_user }}

- hosts: rasprime
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Copy unit file for systemd
      template: src=files/etc/systemd/system/eer.service dest=/etc/systemd/system/eer.service mode=644
    - name: Reload systemd
      command: systemctl daemon-reload
    - name: Enable eer service
      command: systemctl enable eer.service
    - name: Restart eer service
      service: name=eer state=restarted

- hosts: picamera
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Copy unit file for systemd
      template: src=files/etc/systemd/system/eer.service dest=/etc/systemd/system/eer.service mode=644
    - name: Copy camera unit file for systemd
      template: src=files/etc/systemd/system/eer-camera.service dest=/etc/systemd/system/eer-camera.service mode=644
    - name: Add camera script to PATH
      template: src=files/usr/bin/eer-camera-feed dest=/usr/bin/eer-camera-feed mode=755 owner=root group=root
    - name: Reload systemd
      command: systemctl daemon-reload
    - name: Enable eer service
      command: systemctl enable eer.service
    - name: Restart eer service
      service: name=eer state=restarted

- hosts: topside
  gather_facts: no
  tasks:
    - name: Make a pretty launcher for da NOOBS
      template: src=files/Launcher.desktop dest=~/Desktop mode=700
