- hosts: picamera
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    proxy:
      http_proxy: "http://{{ groups['captain'][0] }}:3128"
      https_proxy: "http://{{ groups['captain'][0] }}:3128"
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
      environment: "{{ proxy }}"
    - name: Install Vim
      apt: name=vim state=latest
      environment: "{{ proxy }}"
    - name: Install Java 8 Runtime
      apt: name=openjdk-8-jre state=latest
      environment: "{{ proxy }}"
    - name: Install htop
      apt: name=htop state=latest
      environment: "{{ proxy }}"
    - name: Install nmap
      apt: name=nmap state=latest
      environment: "{{ proxy }}"
    - name: Install Picamera module
      apt: name=python-picamera state=latest
      environment: "{{ proxy }}"
