- hosts: rasprime
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    proxy:
      http_proxy: "http://{{ groups['captain'][0] }}:3128"
      https_proxy: "http://{{ groups['captain'][0] }}:3128"
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
      environment: "{{ proxy }}"
    - name: Install Vim
      apt: name=vim state=latest
      environment: "{{ proxy }}"
    - name: Install I2C Tools
      apt: name=i2c-tools state=latest
      environment: "{{proxy}}"
    - name: Install htop
      apt: name=htop state=latest
      environment: "{{proxy}}"
    - name: Install Java 8 Runtime
      apt: name=openjdk-8-jre state=latest
      environment: "{{proxy}}"
      tags: java
    - name: Install Python serial module
      apt: name=python-serial state=latest
      environment: "{{proxy}}"
